name: 提交 Bug（Bug Report）
description: 请告诉我APP存在的问题，我尽力修复它！（Please tell me the problem with the APP and I will try my best to fix it!）
title: "[Bug]: "
labels: ["bug"]
assignees:
  - pppscn
body:
  - type: markdown
    attributes:
      value: |
        警告：请务必按照 issue 模板填写，避免浪费你我的时间！没有按照模板认真填写，一律直接关闭！
        Warning: Please fill in according to the issue template to avoid wasting your time and mine! If you do not fill in the template carefully, it will be closed directly.
  - type: dropdown
    id: similar-issues
    attributes:
      label: 是否有人曾提过类似的问题【必答】
      description: Whether someone has raised similar issues [Required]
      options:
        - 否（No）
        - 是（Yes）
    validations:
      required: true
  - type: dropdown
    id: latest-version
    attributes:
      label: 升级到最新的版本是否存在这个问题【必答】
      description: Is there this problem when upgrading to the latest version [Required]
      options:
        - 否（No）
        - 是（Yes）
    validations:
      required: true
  - type: dropdown
    id: read-wiki
    attributes:
      label: 是否已经查阅Wiki文档还未能解决的【必答】
      description: Whether you have consulted the Wiki documentation that has not been resolved [Required]
      options:
        - 否（No）
        - 是（Yes）
    validations:
      required: true
  - type: input
    id: app-version
    attributes:
      label: APP版本【必填】
      description: APP Version [Required]
      placeholder: v3.x.x
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: 问题描述【必填】
      description: Description of the problem [Required]
      placeholder: 你可以描述APP有什么令你不满意的地方（You can describe what dissatisfied you about the app）
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: 复现步骤【必填】
      description: Reproduction steps [Required]
      placeholder: 注意：目前不受理没有复现步骤的 Bug 单 (Note：Bug tickets without reproduction steps are currently not accepted)
    validations:
      required: true
  - type: dropdown
    id: required
    attributes:
      label: 是否必现【必填】
      description: Whether it is required [Required]
      options:
        - 否（No）
        - 是（Yes）
    validations:
      required: true
  - type: input
    id: brand-model
    attributes:
      label: 出现问题的手机信息【必填】
      description: The mobile phone information with the problem [Required]
      placeholder: 请填写出现问题的品牌和机型（Please fill in the brand and model of the problem）
    validations:
      required: true
  - type: input
    id: android-version
    attributes:
      label: 出现问题的安卓版本、系统版本【必填】
      description: Android version, system version in question [Required]
      placeholder: 例如：Android 12、MIUI 13
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: 提供截图或视频
      description: Provide screenshots or videos
      placeholder: 如果有报错的话必填 (if there is an error, please fill in)
  - type: textarea
    id: stack
    attributes:
      label: 提供报错堆栈
      description: Provide a stack trace
      placeholder: 根据需要提供，此项不强制 (as needed, this is not mandatory)
  - type: textarea
    id: solution
    attributes:
      label: 提供解决方案
      description: Provide a solution
      placeholder: 如果已经解决了的话可以写下你的解决方法，此项不强制 (if it has been solved, this is not mandatory)